//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1Xamrin.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test1Xamrin.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string AlertLabelMessaggio {
            get {
                return ResourceManager.GetString("AlertLabelMessaggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string CellaClienteParolaRecapito {
            get {
                return ResourceManager.GetString("CellaClienteParolaRecapito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string CellaDocumentoParolaDel {
            get {
                return ResourceManager.GetString("CellaDocumentoParolaDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoice.
        /// </summary>
        internal static string CellaDocumentoParolaFattura {
            get {
                return ResourceManager.GetString("CellaDocumentoParolaFattura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        internal static string CellaDocumentoParolaGenerata {
            get {
                return ResourceManager.GetString("CellaDocumentoParolaGenerata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receipt.
        /// </summary>
        internal static string CellaDocumentoParolaRicevuta {
            get {
                return ResourceManager.GetString("CellaDocumentoParolaRicevuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not enabled.
        /// </summary>
        internal static string ChiamateWSGetCheckVersioneMessaggioDeviceNonAbilitata {
            get {
                return ResourceManager.GetString("ChiamateWSGetCheckVersioneMessaggioDeviceNonAbilitata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version lower than allowed: download version.
        /// </summary>
        internal static string ChiamateWSGetCheckVersioneMessaggioVersInfACons {
            get {
                return ResourceManager.GetString("ChiamateWSGetCheckVersioneMessaggioVersInfACons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version higher than allowed: download version.
        /// </summary>
        internal static string ChiamateWSGetCheckVersioneMessaggioVersSupACons {
            get {
                return ResourceManager.GetString("ChiamateWSGetCheckVersioneMessaggioVersSupACons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in connecting to the database.
        /// </summary>
        internal static string ChiamateWSPostRegistraDeviceMessaggioErroreConnessioneDB {
            get {
                return ResourceManager.GetString("ChiamateWSPostRegistraDeviceMessaggioErroreConnessioneDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving the device.
        /// </summary>
        internal static string ChiamateWSPostRegistraDeviceMessaggioErroreSalvataggioDevice {
            get {
                return ResourceManager.GetString("ChiamateWSPostRegistraDeviceMessaggioErroreSalvataggioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device parameter is null.
        /// </summary>
        internal static string ChiamateWSPostRegistraDeviceMessaggioParametroDeviceNullo {
            get {
                return ResourceManager.GetString("ChiamateWSPostRegistraDeviceMessaggioParametroDeviceNullo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string DatePickerParolaAnno {
            get {
                return ResourceManager.GetString("DatePickerParolaAnno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DatePickerParolaGiorno {
            get {
                return ResourceManager.GetString("DatePickerParolaGiorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string DatePickerParolaMese {
            get {
                return ResourceManager.GetString("DatePickerParolaMese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick date.
        /// </summary>
        internal static string DatePickerTitolo {
            get {
                return ResourceManager.GetString("DatePickerTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request n..
        /// </summary>
        internal static string DescrRichiestaFatturaNum {
            get {
                return ResourceManager.GetString("DescrRichiestaFatturaNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal code:.
        /// </summary>
        internal static string FormClientiCellLabelCodiceFiscale {
            get {
                return ResourceManager.GetString("FormClientiCellLabelCodiceFiscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number:.
        /// </summary>
        internal static string FormClientiCellLabelPIVA {
            get {
                return ResourceManager.GetString("FormClientiCellLabelPIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR is not standard .
        /// </summary>
        internal static string FormClientiMessaggioQRNonStandard {
            get {
                return ResourceManager.GetString("FormClientiMessaggioQRNonStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select county.
        /// </summary>
        internal static string FormClientiTestoSelezionaProvincia {
            get {
                return ResourceManager.GetString("FormClientiTestoSelezionaProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        internal static string FormClientiTestoSelezionaStato {
            get {
                return ResourceManager.GetString("FormClientiTestoSelezionaStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data.
        /// </summary>
        internal static string FormDettClienteLabelAltriDati {
            get {
                return ResourceManager.GetString("FormDettClienteLabelAltriDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string FormDettClienteLblCAP {
            get {
                return ResourceManager.GetString("FormDettClienteLblCAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIG.
        /// </summary>
        internal static string FormDettClienteLblCIG {
            get {
                return ResourceManager.GetString("FormDettClienteLblCIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal code.
        /// </summary>
        internal static string FormDettClienteLblCodFisc {
            get {
                return ResourceManager.GetString("FormDettClienteLblCodFisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State code.
        /// </summary>
        internal static string FormDettClienteLblCodiceStato {
            get {
                return ResourceManager.GetString("FormDettClienteLblCodiceStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string FormDettClienteLblComune {
            get {
                return ResourceManager.GetString("FormDettClienteLblComune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP.
        /// </summary>
        internal static string FormDettClienteLblCUP {
            get {
                return ResourceManager.GetString("FormDettClienteLblCUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intention declaration.
        /// </summary>
        internal static string FormDettClienteLblDichiarazioneIntento {
            get {
                return ResourceManager.GetString("FormDettClienteLblDichiarazioneIntento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string FormDettClienteLblEmail {
            get {
                return ResourceManager.GetString("FormDettClienteLblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact email.
        /// </summary>
        internal static string FormDettClienteLblEmailContatto {
            get {
                return ResourceManager.GetString("FormDettClienteLblEmailContatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string FormDettClienteLblIndirizzo {
            get {
                return ResourceManager.GetString("FormDettClienteLblIndirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string FormDettClienteLblIsPrivate {
            get {
                return ResourceManager.GetString("FormDettClienteLblIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        internal static string FormDettClienteLblNomeContatto {
            get {
                return ResourceManager.GetString("FormDettClienteLblNomeContatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public administration.
        /// </summary>
        internal static string FormDettClienteLblPA {
            get {
                return ResourceManager.GetString("FormDettClienteLblPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pec.
        /// </summary>
        internal static string FormDettClienteLblPec {
            get {
                return ResourceManager.GetString("FormDettClienteLblPec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID Number.
        /// </summary>
        internal static string FormDettClienteLblPIVA {
            get {
                return ResourceManager.GetString("FormDettClienteLblPIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string FormDettClienteLblProvincia {
            get {
                return ResourceManager.GetString("FormDettClienteLblProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string FormDettClienteLblRagioneSociale {
            get {
                return ResourceManager.GetString("FormDettClienteLblRagioneSociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination code.
        /// </summary>
        internal static string FormDettClienteLblSID {
            get {
                return ResourceManager.GetString("FormDettClienteLblSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liable for tax deduction.
        /// </summary>
        internal static string FormDettClienteLblSoggettoARitenuta {
            get {
                return ResourceManager.GetString("FormDettClienteLblSoggettoARitenuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split payment.
        /// </summary>
        internal static string FormDettClienteLblSplitPayment {
            get {
                return ResourceManager.GetString("FormDettClienteLblSplitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string FormDettClienteLblStato {
            get {
                return ResourceManager.GetString("FormDettClienteLblStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string FormDettClienteLblTelefono {
            get {
                return ResourceManager.GetString("FormDettClienteLblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact telephone.
        /// </summary>
        internal static string FormDettClienteLblTelefonoContatto {
            get {
                return ResourceManager.GetString("FormDettClienteLblTelefonoContatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tax code.
        /// </summary>
        internal static string FormDettClienteLblTipoAliquota {
            get {
                return ResourceManager.GetString("FormDettClienteLblTipoAliquota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in connecting to the server. It is not possible to determine if the applicant already exists on the server..
        /// </summary>
        internal static string FormDettClienteMessaggioErroreClienteSuServer {
            get {
                return ResourceManager.GetString("FormDettClienteMessaggioErroreClienteSuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in connecting to the server. It is not possible to determine if the receipt number is already used in another invoice request to the same gas station.
        /// </summary>
        internal static string FormDettClienteMessaggioErroreControlloNumScontrSuServer {
            get {
                return ResourceManager.GetString("FormDettClienteMessaggioErroreControlloNumScontrSuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are fields in state of errore or required fields are missing, scroll the page down vertically..
        /// </summary>
        internal static string FormDettClienteMessaggioPresentiCampiInErrore {
            get {
                return ResourceManager.GetString("FormDettClienteMessaggioPresentiCampiInErrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete applicant because invoice requests with it have already been inserted.
        /// </summary>
        internal static string FormDettClienteMsgImpossCancRichiedenteEsistonoRichFatt {
            get {
                return ResourceManager.GetString("FormDettClienteMsgImpossCancRichiedenteEsistonoRichFatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to edit tax ID number because invoice requests with it have already been inserted.
        /// </summary>
        internal static string FormDettClienteMsgImpossModPIVAEsistonoRichFatt {
            get {
                return ResourceManager.GetString("FormDettClienteMsgImpossModPIVAEsistonoRichFatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID Number already exists..
        /// </summary>
        internal static string FormDettClienteMsgPartitaIvaGiaPres {
            get {
                return ResourceManager.GetString("FormDettClienteMsgPartitaIvaGiaPres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code is required..
        /// </summary>
        internal static string FormDettClienteValidazioniCAP {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniCAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIG must be at most 15 characters long..
        /// </summary>
        internal static string FormDettClienteValidazioniCIG {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniCIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State code is required..
        /// </summary>
        internal static string FormDettClienteValidazioniCodiceStato {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniCodiceStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        internal static string FormDettClienteValidazioniComune {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniComune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP must be at most 15 characters long..
        /// </summary>
        internal static string FormDettClienteValidazioniCUP {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniCUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string FormDettClienteValidazioniEmail {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not valid..
        /// </summary>
        internal static string FormDettClienteValidazioniEmail2 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal code is required..
        /// </summary>
        internal static string FormDettClienteValidazioniFiscalCode1 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniFiscalCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal code must be 11 or 16 characters long..
        /// </summary>
        internal static string FormDettClienteValidazioniFiscalCode2 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniFiscalCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If fiscal code is 11 characters long, it must consist only of digits..
        /// </summary>
        internal static string FormDettClienteValidazioniFiscalCode3 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniFiscalCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        internal static string FormDettClienteValidazioniIndirizzo {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniIndirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pec is required..
        /// </summary>
        internal static string FormDettClienteValidazioniPec {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pec not valid..
        /// </summary>
        internal static string FormDettClienteValidazioniPec2 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number is required..
        /// </summary>
        internal static string FormDettClienteValidazioniPIVA1 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPIVA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number must be 11 character long..
        /// </summary>
        internal static string FormDettClienteValidazioniPIVA2 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPIVA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number must be 16 character long..
        /// </summary>
        internal static string FormDettClienteValidazioniPIVA2Vers16 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPIVA2Vers16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number must consist only of digits..
        /// </summary>
        internal static string FormDettClienteValidazioniPIVA3 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniPIVA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County is required..
        /// </summary>
        internal static string FormDettClienteValidazioniProv {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required..
        /// </summary>
        internal static string FormDettClienteValidazioniRagSoc {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniRagSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination code is required or invalid length (6 for public admnistration, 7 for private)..
        /// </summary>
        internal static string FormDettClienteValidazioniSID1 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniSID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it is a public administration destination code must be 6 characters long, otherwise 7 characters long..
        /// </summary>
        internal static string FormDettClienteValidazioniSID2 {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniSID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        internal static string FormDettClienteValidazioniStato {
            get {
                return ResourceManager.GetString("FormDettClienteValidazioniStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string FormDocumentiBtnCerca {
            get {
                return ResourceManager.GetString("FormDocumentiBtnCerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station.
        /// </summary>
        internal static string FormDocumentiLabelSceltaBenzinaio {
            get {
                return ResourceManager.GetString("FormDocumentiLabelSceltaBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string FormDocumentiLblAData {
            get {
                return ResourceManager.GetString("FormDocumentiLblAData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string FormDocumentiLblDaData {
            get {
                return ResourceManager.GetString("FormDocumentiLblDaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string FormDocumentiLblDocApprovati {
            get {
                return ResourceManager.GetString("FormDocumentiLblDocApprovati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To approve.
        /// </summary>
        internal static string FormDocumentiLblDocDaApprovare {
            get {
                return ResourceManager.GetString("FormDocumentiLblDocDaApprovare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string FormDocumentiLblDocRespinti {
            get {
                return ResourceManager.GetString("FormDocumentiLblDocRespinti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All requests.
        /// </summary>
        internal static string FormDocumentiLblDocTutti {
            get {
                return ResourceManager.GetString("FormDocumentiLblDocTutti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string FormDocumentiParolaRespinta {
            get {
                return ResourceManager.GetString("FormDocumentiParolaRespinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string FormDocumentiPlaceholderDate {
            get {
                return ResourceManager.GetString("FormDocumentiPlaceholderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATIONx.
        /// </summary>
        internal static string FormMenuBottone1 {
            get {
                return ResourceManager.GetString("FormMenuBottone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE REQUEST.
        /// </summary>
        internal static string FormMenuBottone2 {
            get {
                return ResourceManager.GetString("FormMenuBottone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUESTS LIST.
        /// </summary>
        internal static string FormMenuBottone2Vers2 {
            get {
                return ResourceManager.GetString("FormMenuBottone2Vers2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string FormMenuBottone3 {
            get {
                return ResourceManager.GetString("FormMenuBottone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not available.
        /// </summary>
        internal static string FormMenuMessaggioErroreCameraNonDisp {
            get {
                return ResourceManager.GetString("FormMenuMessaggioErroreCameraNonDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is busy. Try again.
        /// </summary>
        internal static string FormMenuMessaggioErroreCameraOccupata {
            get {
                return ResourceManager.GetString("FormMenuMessaggioErroreCameraOccupata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture taken correctl: size = .
        /// </summary>
        internal static string FormMenuMessaggioFotoEsegCorrettamente {
            get {
                return ResourceManager.GetString("FormMenuMessaggioFotoEsegCorrettamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        internal static string FormMenuMessaggioOperazioneAnnullata {
            get {
                return ResourceManager.GetString("FormMenuMessaggioOperazioneAnnullata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture already present, do you wish to overwrite it?.
        /// </summary>
        internal static string FormNuovoDocDomandaSovrasciviImmagine {
            get {
                return ResourceManager.GetString("FormNuovoDocDomandaSovrasciviImmagine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR already present, do you wish to overwrite it?.
        /// </summary>
        internal static string FormNuovoDocDomandaSovrasciviQR {
            get {
                return ResourceManager.GetString("FormNuovoDocDomandaSovrasciviQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station.
        /// </summary>
        internal static string FormNuovoDocLabelSceltaBenzinaio {
            get {
                return ResourceManager.GetString("FormNuovoDocLabelSceltaBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose registration.
        /// </summary>
        internal static string FormNuovoDocLabelSelCliente {
            get {
                return ResourceManager.GetString("FormNuovoDocLabelSelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose payment method.
        /// </summary>
        internal static string FormNuovoDocLabelSelModPagamento {
            get {
                return ResourceManager.GetString("FormNuovoDocLabelSelModPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        internal static string FormNuovoDocLblCliente {
            get {
                return ResourceManager.GetString("FormNuovoDocLblCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string FormNuovoDocLblCodiceProdotto {
            get {
                return ResourceManager.GetString("FormNuovoDocLblCodiceProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt picture 2.
        /// </summary>
        internal static string FormNuovoDocLblFoto2Scontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblFoto2Scontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt picture 3.
        /// </summary>
        internal static string FormNuovoDocLblFoto3Scontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblFoto3Scontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string FormNuovoDocLblKM {
            get {
                return ResourceManager.GetString("FormNuovoDocLblKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type.
        /// </summary>
        internal static string FormNuovoDocLblModPagamento {
            get {
                return ResourceManager.GetString("FormNuovoDocLblModPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string FormNuovoDocLblNoteScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblNoteScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt nr..
        /// </summary>
        internal static string FormNuovoDocLblNumScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblNumScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pump n..
        /// </summary>
        internal static string FormNuovoDocLblPompaScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblPompaScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        internal static string FormNuovoDocLblPrezzoUnitario {
            get {
                return ResourceManager.GetString("FormNuovoDocLblPrezzoUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sale.
        /// </summary>
        internal static string FormNuovoDocLblPuntoVenditaScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblPuntoVenditaScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read receipt QR.
        /// </summary>
        internal static string FormNuovoDocLblQRScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblQRScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied quantity.
        /// </summary>
        internal static string FormNuovoDocLblQuantita {
            get {
                return ResourceManager.GetString("FormNuovoDocLblQuantita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date.
        /// </summary>
        internal static string FormNuovoDocLblReceiptDate {
            get {
                return ResourceManager.GetString("FormNuovoDocLblReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string FormNuovoDocLblTarga {
            get {
                return ResourceManager.GetString("FormNuovoDocLblTarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal n..
        /// </summary>
        internal static string FormNuovoDocLblTerminaleScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocLblTerminaleScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product total.
        /// </summary>
        internal static string FormNuovoDocLblTotPagato {
            get {
                return ResourceManager.GetString("FormNuovoDocLblTotPagato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image to delete.
        /// </summary>
        internal static string FormNuovoDocMessaggioNessunaImmPresDaCancellare {
            get {
                return ResourceManager.GetString("FormNuovoDocMessaggioNessunaImmPresDaCancellare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image to view.
        /// </summary>
        internal static string FormNuovoDocMessaggioNessunaImmPresDaVisualizzare {
            get {
                return ResourceManager.GetString("FormNuovoDocMessaggioNessunaImmPresDaVisualizzare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No QR to delete.
        /// </summary>
        internal static string FormNuovoDocMessaggioNessunQRPresDaCancellare {
            get {
                return ResourceManager.GetString("FormNuovoDocMessaggioNessunQRPresDaCancellare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt number already used in another invoice request to the same gas station.
        /// </summary>
        internal static string FormNuovoDocMessaggioNumScontrinoGiaPresenteBenzinaio {
            get {
                return ResourceManager.GetString("FormNuovoDocMessaggioNumScontrinoGiaPresenteBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one tax ID number must be registered before proceeding with the request of an invoice.
        /// </summary>
        internal static string FormNuovoDocMsgInserireAlmenoUnCliente {
            get {
                return ResourceManager.GetString("FormNuovoDocMsgInserireAlmenoUnCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert gas station before selecting payment method.
        /// </summary>
        internal static string FormNuovoDocMsgIntrodurreBenzinaioPrimaSelModPag {
            get {
                return ResourceManager.GetString("FormNuovoDocMsgIntrodurreBenzinaioPrimaSelModPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert gas station before selecting the product.
        /// </summary>
        internal static string FormNuovoDocMsgIntrodurreBenzinaioPrimaSelProdotto {
            get {
                return ResourceManager.GetString("FormNuovoDocMsgIntrodurreBenzinaioPrimaSelProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert applicant before selecting the gas station.
        /// </summary>
        internal static string FormNuovoDocMsgIntrodurreRichiedentePrimaSelBenzinaio {
            get {
                return ResourceManager.GetString("FormNuovoDocMsgIntrodurreRichiedentePrimaSelBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert total amount before selecting the product.
        /// </summary>
        internal static string FormNuovoDocMsgIntrodurreTotalePrimaSelProdotto {
            get {
                return ResourceManager.GetString("FormNuovoDocMsgIntrodurreTotalePrimaSelProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string FormNuovoDocPlaceholderDate {
            get {
                return ResourceManager.GetString("FormNuovoDocPlaceholderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string FormNuovoDocPlaceholderKM {
            get {
                return ResourceManager.GetString("FormNuovoDocPlaceholderKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string FormNuovoDocPlaceholderTarga {
            get {
                return ResourceManager.GetString("FormNuovoDocPlaceholderTarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases product.
        /// </summary>
        internal static string FormNuovoDocSeparatoreLblCarburante {
            get {
                return ResourceManager.GetString("FormNuovoDocSeparatoreLblCarburante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select.
        /// </summary>
        internal static string FormNuovoDocTapparePerInsModPag {
            get {
                return ResourceManager.GetString("FormNuovoDocTapparePerInsModPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sel. gas station.
        /// </summary>
        internal static string FormNuovoDocTestoSelezionaBenzinaio {
            get {
                return ResourceManager.GetString("FormNuovoDocTestoSelezionaBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select.
        /// </summary>
        internal static string FormNuovoDocUsareListaPerInsModCodiceProdotto {
            get {
                return ResourceManager.GetString("FormNuovoDocUsareListaPerInsModCodiceProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniBenzinaio {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniBenzinaio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniCliente {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniDataScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniDataScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A picture of the receipt must be taken..
        /// </summary>
        internal static string FormNuovoDocValidazioniFotoScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniFotoScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt note is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniNoteScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniNoteScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt number is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniNumScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniNumScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt time is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniOraScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniOraScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt pump number is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniPompaScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniPompaScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniProdotto {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt point of sale is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniPuntoVenditaScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniPuntoVenditaScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt QR is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniQRScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniQRScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniTarga {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate must be at least 3 characters long..
        /// </summary>
        internal static string FormNuovoDocValidazioniTargaLunghezza {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTargaLunghezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt terminal number is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniTerminaleScontrino {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTerminaleScontrino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniTipoPag {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTipoPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount is required..
        /// </summary>
        internal static string FormNuovoDocValidazioniTotale {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount must be greater than zero..
        /// </summary>
        internal static string FormNuovoDocValidazioniTotaleMaggZero {
            get {
                return ResourceManager.GetString("FormNuovoDocValidazioniTotaleMaggZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self:.
        /// </summary>
        internal static string FormPrezziLblSelfService {
            get {
                return ResourceManager.GetString("FormPrezziLblSelfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Served:.
        /// </summary>
        internal static string FormPrezziLblServito {
            get {
                return ResourceManager.GetString("FormPrezziLblServito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string FormPrezziLblServitoVersioneNoSelf {
            get {
                return ResourceManager.GetString("FormPrezziLblServitoVersioneNoSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on one of the buttons to select.
        /// </summary>
        internal static string FormSceltaProdottoLblTitolo {
            get {
                return ResourceManager.GetString("FormSceltaProdottoLblTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice preview.
        /// </summary>
        internal static string FormSincroBottoneAnteprimaFattura {
            get {
                return ResourceManager.GetString("FormSincroBottoneAnteprimaFattura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FormSincroBottoneEsci {
            get {
                return ResourceManager.GetString("FormSincroBottoneEsci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string FormSincroBottoneSincroLabelInvia {
            get {
                return ResourceManager.GetString("FormSincroBottoneSincroLabelInvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract date.
        /// </summary>
        internal static string FormSincroRiepilogoLabelDataContratto {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelDataContratto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement date.
        /// </summary>
        internal static string FormSincroRiepilogoLabelDataConvenzione {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelDataConvenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        internal static string FormSincroRiepilogoLabelDataOrdine {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelDataOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception date.
        /// </summary>
        internal static string FormSincroRiepilogoLabelDataRicezione {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelDataRicezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string FormSincroRiepilogoLabelNomeDitta {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelNomeDitta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract number.
        /// </summary>
        internal static string FormSincroRiepilogoLabelNumContratto {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelNumContratto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement number.
        /// </summary>
        internal static string FormSincroRiepilogoLabelNumConvenzione {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelNumConvenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string FormSincroRiepilogoLabelNumOrdine {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelNumOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception number.
        /// </summary>
        internal static string FormSincroRiepilogoLabelNumRicezione {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelNumRicezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string FormSincroRiepilogoLabelProdotto {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string FormSincroRiepilogoLabelRecapito {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelRecapito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request review.
        /// </summary>
        internal static string FormSincroRiepilogoLabelRiepilgoRichiesta {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelRiepilgoRichiesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        internal static string FormSincroRiepilogoLabelTarga {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelTarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string FormSincroRiepilogoLabelTotalePagato {
            get {
                return ResourceManager.GetString("FormSincroRiepilogoLabelTotalePagato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic error.
        /// </summary>
        internal static string FormWSChiamateMetodoDevEnabledMsgErroreGenerico {
            get {
                return ResourceManager.GetString("FormWSChiamateMetodoDevEnabledMsgErroreGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http code execution error: .
        /// </summary>
        internal static string FormWSChiamateMetodoDevEnabledMsgErroreHTTP {
            get {
                return ResourceManager.GetString("FormWSChiamateMetodoDevEnabledMsgErroreHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm cancellation?.
        /// </summary>
        internal static string MessaggioConfermaCancellazione {
            get {
                return ResourceManager.GetString("MessaggioConfermaCancellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information from server.
        /// </summary>
        internal static string NuovoHudColoratoMessaggioAttesa {
            get {
                return ResourceManager.GetString("NuovoHudColoratoMessaggioAttesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string NuovoHudColoratoMessaggioSalvataggio {
            get {
                return ResourceManager.GetString("NuovoHudColoratoMessaggioSalvataggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchbarClientiPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarClientiPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string SearchbarDocumentiPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarDocumentiPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is required.
        /// </summary>
        internal static string SincroConnessioneInternet {
            get {
                return ResourceManager.GetString("SincroConnessioneInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in sending data to the server: system will try again next time application will be opened.
        /// </summary>
        internal static string SincroMessErrore {
            get {
                return ResourceManager.GetString("SincroMessErrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TestoBtnAnnulla {
            get {
                return ResourceManager.GetString("TestoBtnAnnulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TestoBtnAnnullaDocumento {
            get {
                return ResourceManager.GetString("TestoBtnAnnullaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TestoBtnChiudiDocumento {
            get {
                return ResourceManager.GetString("TestoBtnChiudiDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TestoBtnSalva {
            get {
                return ResourceManager.GetString("TestoBtnSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TestoBtnSalvaDocumento {
            get {
                return ResourceManager.GetString("TestoBtnSalvaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station selection.
        /// </summary>
        internal static string TitoloFormBenzinai {
            get {
                return ResourceManager.GetString("TitoloFormBenzinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        internal static string TitoloFormClienti {
            get {
                return ResourceManager.GetString("TitoloFormClienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration detail.
        /// </summary>
        internal static string TitoloFormDettCliente {
            get {
                return ResourceManager.GetString("TitoloFormDettCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data.
        /// </summary>
        internal static string TitoloFormDettClienteAltriDati {
            get {
                return ResourceManager.GetString("TitoloFormDettClienteAltriDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request list.
        /// </summary>
        internal static string TitoloFormDocumenti {
            get {
                return ResourceManager.GetString("TitoloFormDocumenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit invoice request.
        /// </summary>
        internal static string TitoloFormModDoc {
            get {
                return ResourceManager.GetString("TitoloFormModDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New registration.
        /// </summary>
        internal static string TitoloFormNuovoCliente {
            get {
                return ResourceManager.GetString("TitoloFormNuovoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New invoice request.
        /// </summary>
        internal static string TitoloFormNuovoDoc {
            get {
                return ResourceManager.GetString("TitoloFormNuovoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data.
        /// </summary>
        internal static string TitoloFormNuovoDocAltriDati {
            get {
                return ResourceManager.GetString("TitoloFormNuovoDocAltriDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products selection.
        /// </summary>
        internal static string TitoloFormSceltaProdotti {
            get {
                return ResourceManager.GetString("TitoloFormSceltaProdotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County selection.
        /// </summary>
        internal static string TitoloFormSceltaProvincia {
            get {
                return ResourceManager.GetString("TitoloFormSceltaProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country selection.
        /// </summary>
        internal static string TitoloFormSceltaStato {
            get {
                return ResourceManager.GetString("TitoloFormSceltaStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string TitoloFormSincroRiepilogo {
            get {
                return ResourceManager.GetString("TitoloFormSincroRiepilogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture view.
        /// </summary>
        internal static string TitoloFormVisualizzazioneFoto {
            get {
                return ResourceManager.GetString("TitoloFormVisualizzazioneFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number not valid.
        /// </summary>
        internal static string VerificaPartitaIVAMessaggioPIVAnonValida {
            get {
                return ResourceManager.GetString("VerificaPartitaIVAMessaggioPIVAnonValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID number valid.
        /// </summary>
        internal static string VerificaPartitaIVAMessaggioPIVAvalida {
            get {
                return ResourceManager.GetString("VerificaPartitaIVAMessaggioPIVAvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save data.
        /// </summary>
        internal static string VerificaPartitaIVAMessaggioSiDesideraSalvareDati {
            get {
                return ResourceManager.GetString("VerificaPartitaIVAMessaggioSiDesideraSalvareDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following data have been found.
        /// </summary>
        internal static string VerificaPartitaIVAMessaggioTrovatiSeguentiDati {
            get {
                return ResourceManager.GetString("VerificaPartitaIVAMessaggioTrovatiSeguentiDati", resourceCulture);
            }
        }
    }
}
